### ISSUE TITLE
Duplicate int 0x20 in sieve.asm

### ISSUE THREAD

**Issue by jcross** [nanochess/book8088#1]
https://github.com/nanochess/book8088/blob/fd8152ab229730d6b57a6c1707595ac54d92109c/sieve.asm#L40

This int 0x20 seems to be redundant with the one already added by pasting in library2.asm. It also does not appear in the listing for p3 on page 28 in the book itself. It doesn't affect the functionality at all but it does burn two unnecessary bytes. The extra bytes are included in the 123 byte count for the program mentioned on page 28. That's how I noticed the mistake in the first place. Following the instructions as written in the book produces a 121 byte binary.

**Comment by nanochess** [comment]
Thanks for your report! I've corrected it, and added a note about the 123 byte count.
