### ISSUE TITLE
# Problems with Hello World Program (first.asm)

### ISSUE THREAD

**Issue by u123b** [nanochess/book8088#2]
I wan't to run the "Hello World example" (first.asm) from the book "PROGRAMMING BOOT SECTOR GAMES" but every time I run it, I get this error "Die Version von C:\Test\asm\bootgames\book\noob\v1_test_hello_world_64_bit\v1.com ist mit der ausgeführten Windows-Version nicht kompatibel. Überprüfen Sie die Systeminformationen des Computers, und wenden Sie sich anschließend an den Herausgeber der Software." (roughly translated "The version of C:\Test\asm\bootgames\book\noob\v1_test_hello_world_64_bit\v1.com is not compatible with the running version of Windows. Check the System information of your PC and contact the software developer.")
(If someone is interested I have a AMD CPU with Windows 10 x64.)

**Comment by nanochess** [comment]
Starting with Windows 8, all support for original COM/EXE executables in DOS was removed. You should use DosBox to run COM files on Windows 10.

**Comment by u123b** [comment]
Thank's for the answer, can I also use QEMU and compile it to a bin file instead of a com file?

**Comment by nanochess** [comment]
> Thank's for the answer, can I also use QEMU and compile it to a bin file instead of a com file?

Yes, of course.
